#!/usr/bin/env julia
#
# Citation-link maintenance for the design docs (rewrite plan, Phase 1.1).
#
# Citations are kept as reference-style markdown links with a generated
# definitions block at the bottom of each file mapping every used label to its
# heading anchor. Body text therefore carries no anchor slugs, and a renumbering
# only rewrites the visible tokens and regenerates the tables.
#
# Two citation classes, one mechanism. Section citations (`§N`, `§N.M`, `§X.N`,
# `Appendix X`) are owned by framework_spec.md and labelled `s9-4`; decision
# citations (`D-037`) are owned by framework_decisions.md and labelled `d-037`.
# Each label resolves against whichever document owns it — in-file when that is
# the file being linked (`[s9-4]: #94-…` in the spec, `[d-037]: #d-037--…` in
# the log), cross-file otherwise (`[d-037]: framework_decisions.md#d-037--…`).
# A range links its endpoints, `D-166–D-168` becoming two links around the dash.
#
# Four jobs, all idempotent — re-run after any renumbering or renaming and the
# links, the definition blocks, the table of contents and the decision index
# regenerate against the new headings:
#
#   1. Convert citations to reference links: bare tokens, legacy inline links
#      (`[§9.4](#slug)` pointing at the spec) and stale reference links alike
#      all normalize to `[tok][label]` with the label derived from the token.
#   2. Regenerate each file's definitions block (only the labels the file uses,
#      sorted; everything from the marker line to EOF is owned by the block).
#   3. Regenerate the spec's `## Contents` between the front matter and
#      `# Part I` (inline links; the TOC is generated wholesale, so its slugs
#      never rot).
#   4. Regenerate the decision log's `## Index` from its own entry headings and
#      `**Status.**` lines, likewise wholesale, so the index cannot drift from
#      the entries it lists.
#
# Never touched: fenced code blocks, inline code spans, heading lines, links
# whose text is not a citation token (the TOC), and a companion's explicit
# in-file links (`[§N](#own-slug)` in a walkthrough citing itself).
#
# The walkthroughs cite their own numbered sections, so a bare `§N` in one of
# them is ambiguous: it may mean the walkthrough's own §N or the spec's. Such
# tokens are left alone and warned about — the author resolves them by writing
# an explicit in-file link, which then survives every later run untouched.
#
# framework_decisions.md is processed like any other companion. Its earlier
# exclusion was a property of its retired table form. Its `## Index` rows are
# skipped by job 1 only because job 4 owns them outright.
#
# Run from anywhere:  julia docs/notes/design/tools/linkify.jl

include(joinpath(@__DIR__, "slugs.jl"))

const DESIGN = normpath(joinpath(@__DIR__, ".."))
const SPEC = "framework_spec.md"
const DECISIONS = "framework_decisions.md"

const COMPANIONS = ["framework_decisions.md",
                    "framework_extensions.md",
                    "event_visibility_walkthrough.md",
                    "inbound_periphery_walkthrough.md",
                    "trim_environment_walkthrough.md",
                    "frozen_discrete_walkthrough.md",
                    "localization_validation_walkthrough.md",
                    "sample_time_proposal.md"]

# Companions that cite their own numbered sections (the walkthroughs). Only
# here is a bare `§N` ambiguous between the file and the spec.
const SELF_CITING = ["event_visibility_walkthrough.md",
                     "inbound_periphery_walkthrough.md"]

const MARKER = "<!-- citation link definitions — generated by tools/linkify.jl; do not edit -->"

# Scanned left to right. Code spans and both link forms are matched so the
# replacer can either skip or normalize them; the rest are bare citations.
const SCAN = r"`+[^`]*`+|\[[^\]]*\]\([^)]*\)|\[[^\]]*\]\[[^\]]*\]|§\d+(?:\.\d+)?|§[A-D]\.\d+|Appendix [A-D](?![\w–—-])|\bD-\d+"

const INLINE = r"^\[([^\]]*)\]\(([^)#]*)#([^)]+)\)$"
const REFERENCE = r"^\[([^\]]*)\]\[([^\]]*)\]$"

# Any reference label this tool generates: `s9-4`, `sD-7`, `sC`, `d-037`.
const LABEL = r"(?:s[A-D0-9][A-Za-z0-9-]*|d-\d+)"

isdecision(tok) = startswith(tok, "D-")
iscitation(tok) = isdecision(tok) || startswith(tok, "§") || startswith(tok, "Appendix ")

"Section key for a `§`/`Appendix` token: `§9.4` → `9.4`, `Appendix C` → `C`."
key(tok) = startswith(tok, "§") ? tok[nextind(tok, 1):end] : tok[end:end]

"""
Reference label for a citation token: `§9.4` → `s9-4`, `Appendix C` → `sC`,
`D-037` → `d-037`. The two classes never collide, so one definitions block per
file carries both — each label resolving to whichever document owns it.
"""
labelof(tok) = isdecision(tok) ? "d-" * tok[3:end] : "s" * replace(key(tok), "." => "-")

"The file's own top-level section numbers — `§N` tokens it may be citing itself with."
function ownsections(file)
    hs = headings(joinpath(DESIGN, file))
    return Set(h.number for h in hs if h.number !== nothing && !occursin('.', h.number))
end

"""
    registry(spechs, loghs) -> Dict{String,Tuple{String,String}}

Every citable label mapped to the document owning its anchor and the anchor's
slug: `§` sections live in the spec, `D-nnn` entries in the decision log. A
label whose owner is the file being linked resolves in-file, everything else
across files — which is what lets one definitions block carry both classes.
"""
function registry(spechs, loghs)
    r = Dict{String,Tuple{String,String}}()
    for (k, slug) in targets(spechs)
        r["s" * replace(k, "." => "-")] = (SPEC, slug)
    end
    for h in loghs
        m = match(r"^D-(\d+) — ", h.text)
        m === nothing || (r["d-" * m[1]] = (DECISIONS, h.slug))
    end
    return r
end

"""
    relink!(file, reg; own) -> (nlinks, ambiguous)

Normalize every citation in `file` to `[tok][label]` form and regenerate the
definitions block. Bare `§` tokens naming one of `own`'s section numbers are
skipped and returned as `(lineno, token)` pairs.
"""
function relink!(file, reg; own = Set{String}())
    path = joinpath(DESIGN, file)
    lines = readlines(path)

    # the definitions block owns everything from the marker to EOF
    stop = findfirst(==(MARKER), lines)
    stop === nothing || (lines = lines[1:stop-1])
    while !isempty(lines) && isempty(strip(lines[end]))
        pop!(lines)
    end

    infence = false
    n = 0
    ambiguous = Tuple{Int,String}[]
    citable(tok) = haskey(reg, labelof(tok))
    for (i, line) in pairs(lines)
        startswith(line, "```") && (infence = !infence; continue)
        (infence || startswith(line, "#")) && continue
        # the log's index is an identifier column, not prose: its `| D-001 |`
        # cells name entries rather than cite them, so they stay literal
        (file == DECISIONS && startswith(lstrip(line), "|")) && continue
        lines[i] = replace(line, SCAN => function (tok)
            startswith(tok, "`") && return tok             # code span
            if startswith(tok, "[")
                m = match(INLINE, tok)
                if m !== nothing                           # legacy inline link
                    iscitation(m[1]) && citable(m[1]) || return tok
                    owner = reg[labelof(m[1])][1]          # a file's own-file
                    m[2] == owner || (m[2] == "" && file == owner) || return tok
                    n += 1                                 # links stay explicit
                    return "[$(m[1])][$(labelof(m[1]))]"
                end
                m = match(REFERENCE, tok)
                if m !== nothing                           # normalize the label
                    iscitation(m[1]) && citable(m[1]) || return tok
                    n += 1
                    return "[$(m[1])][$(labelof(m[1]))]"
                end
                return tok                                 # non-anchor link
            end
            if !isdecision(tok) && key(tok) in own         # bare citation
                push!(ambiguous, (i, tok))
                return tok
            end
            citable(tok) || return tok                     # dangling: check_refs reports it
            n += 1
            return "[$tok][$(labelof(tok))]"
        end)
    end

    # regenerate the definitions block from the labels the body actually uses;
    # fences are skipped and the `s` prefix required so code like `x[1][2]`
    # never reads as a reference link
    used = Set{String}()
    infence = false
    for line in lines
        startswith(line, "```") && (infence = !infence; continue)
        infence && continue
        for m in eachmatch(Regex("\\]\\[(" * LABEL.pattern * ")\\]"), line)
            push!(used, m[1])
        end
    end
    defined = sort!([l for l in used if haskey(reg, l)])
    unknown = sort!([l for l in used if !haskey(reg, l)])
    isempty(unknown) ||
        println("    warn: $file uses labels with no citable heading: ", unknown)
    if !isempty(defined)
        push!(lines, "", MARKER)
        for l in defined
            owner, slug = reg[l]
            push!(lines, "[$l]: $(owner == file ? "" : owner)#$slug")
        end
    end
    write(path, join(lines, "\n") * "\n")
    return n, ambiguous
end

"""
    toc(hs) -> Vector{String}

The `## Contents` block. Parts and the appendix back matter sit at the outer
level, chapters and appendices one level in, sections and the `D.x` glossary
groups two. `####` headings are not listed.
"""
function toc(hs)
    out = ["## Contents", ""]
    for (i, h) in enumerate(hs)
        (i == 1 || h.level >= 4 || h.text == "Contents") && continue
        indent = h.level == 1 ? "" :               # parts, appendix back matter
                 h.level == 2 ? "  " : "    "
        push!(out, "$indent- [$(h.text)](#$(h.slug))")
    end
    push!(out, "")
    return out
end

"An index cell's entry references, linked. Existing links are unwrapped first,
so regenerating an already-linked index is a no-op."
linkstatus(s) = replace(replace(s, r"\[(D-\d+)\]\[d-\d+\]" => s"\1"),
                        r"\bD-\d+" => m -> "[$m][d-$(m[3:end])]")

"""
    reindex!() -> Int

Regenerate the decision log's `## Index` from the entries themselves, so the two
cannot drift: one row per `### D-nnn — Title` heading carrying that entry's
`**Status.**` payload, every identifier linked to its anchor. Everything from
`## Index` to the first entry heading is owned by this block.

Runs before the log is relinked, so the labels it introduces are in place when
the definitions block is regenerated from the labels actually used.
"""
function reindex!()
    path = joinpath(DESIGN, DECISIONS)
    lines = readlines(path)

    ids, titles, statuses = String[], String[], String[]
    pending = false
    for line in lines
        m = match(r"^### D-(\d+) — (.*?)\s*$", line)
        if m !== nothing
            push!(ids, m[1]); push!(titles, m[2]); pending = true
            continue
        end
        s = match(r"^\*\*Status\.\*\* +(.*?)\s*$", line)
        s === nothing || !pending || (push!(statuses, s[1]); pending = false)
    end
    length(ids) == length(statuses) ||
        error("$(length(ids)) entries but $(length(statuses)) status lines")

    block = ["## Index", "", "| ID | Title | Status |", "|---|---|---|"]
    for (id, title, status) in zip(ids, titles, statuses)
        push!(block, "| [D-$id][d-$id] | $title | $(linkstatus(status)) |")
    end
    push!(block, "")

    idx = findfirst(isequal("## Index"), lines)
    idx === nothing && error("`## Index` not found")
    firstentry = findfirst(startswith("### D-"), lines)
    firstentry === nothing && error("no entry headings found")
    idx < firstentry || error("`## Index` does not precede the entries")
    splice!(lines, idx:firstentry-1, block)
    write(path, join(lines, "\n") * "\n")
    return length(ids)
end

"Regenerate the spec's `## Contents` between the front matter and `# Part I`."
function retoc!(hs)
    path = joinpath(DESIGN, SPEC)
    lines = readlines(path)
    part1 = findfirst(startswith("# Part I"), lines)
    part1 === nothing && error("`# Part I` not found")
    old = findfirst(isequal("## Contents"), lines)
    if old !== nothing
        old < part1 || error("`## Contents` is not in the front matter")
        deleteat!(lines, old:part1-1)
        part1 = findfirst(startswith("# Part I"), lines)
    end
    block = [toc(hs); "---"; ""]
    splice!(lines, part1:part1-1, block)
    write(path, join(lines, "\n") * "\n")
    return count(l -> startswith(strip(l), "- ["), block)
end

hs = headings(joinpath(DESIGN, SPEC))
loghs = headings(joinpath(DESIGN, DECISIONS))
reg = registry(hs, loghs)
dup = collisions(hs)
isempty(dup) || println("slug collisions resolved by suffix: ", dup)
logdup = collisions(loghs)
isempty(logdup) || println("log slug collisions resolved by suffix: ", logdup)
println("citable: ", count(l -> startswith(l, "s"), keys(reg)), " sections, ",
        count(l -> startswith(l, "d-"), keys(reg)), " decision entries")

println("relink")
println("  ", rpad("index of $DECISIONS", 42), lpad(reindex!(), 5), " entries")
println("  ", rpad(SPEC, 42), lpad(first(relink!(SPEC, reg)), 5), " links")
for f in COMPANIONS
    n, ambiguous = relink!(f, reg;
                           own = f in SELF_CITING ? ownsections(f) : Set{String}())
    println("  ", rpad(f, 42), lpad(n, 5), " links")
    for (lineno, tok) in ambiguous
        println("    warn: $f:$lineno bare $tok also names this file's own section",
                " — write the link explicitly")
    end
end
println("  contents: ", retoc!(hs), " entries")
