#!/usr/bin/env julia
#
# Citation-link maintenance for the design docs (rewrite plan, Phase 1.1).
#
# Citations (`§N`, `§N.M`, `§X.N`, `Appendix X`) are kept as reference-style
# markdown links — `[§9.4][s9-4]` — with a generated definitions block at the
# bottom of each file mapping every used label to its heading anchor
# (`[s9-4]: #94-…` in the spec, `[s9-4]: framework_spec.md#94-…` in the
# companions). Body text therefore carries no anchor slugs, and a renumbering
# only rewrites the visible tokens and regenerates the tables.
#
# Three jobs, all idempotent — re-run after any renumbering or renaming and the
# links, the definition blocks and the table of contents regenerate against the
# new headings:
#
#   1. Convert citations to reference links: bare tokens, legacy inline links
#      (`[§9.4](#slug)` pointing at the spec) and stale reference links alike
#      all normalize to `[tok][label]` with the label derived from the token.
#   2. Regenerate each file's definitions block (only the labels the file uses,
#      sorted; everything from the marker line to EOF is owned by the block).
#   3. Regenerate the spec's `## Contents` between the front matter and
#      `# Part I` (inline links; the TOC is generated wholesale, so its slugs
#      never rot).
#
# Never touched: fenced code blocks, inline code spans, heading lines, links
# whose text is not a citation token (the TOC), and a companion's explicit
# in-file links (`[§N](#own-slug)` in a walkthrough citing itself).
#
# The walkthroughs cite their own numbered sections, so a bare `§N` in one of
# them is ambiguous: it may mean the walkthrough's own §N or the spec's. Such
# tokens are left alone and warned about — the author resolves them by writing
# an explicit in-file link, which then survives every later run untouched.
#
# framework_decisions.md is deliberately excluded: it is one giant table whose
# rows are edited constantly, and links would clutter every cell's source.
#
# Run from anywhere:  julia docs/notes/design/tools/linkify.jl

include(joinpath(@__DIR__, "slugs.jl"))

const DESIGN = normpath(joinpath(@__DIR__, ".."))
const SPEC = "framework_spec.md"

const COMPANIONS = ["framework_extensions.md",
                    "event_visibility_walkthrough.md",
                    "inbound_periphery_walkthrough.md",
                    "trim_environment_walkthrough.md",
                    "frozen_discrete_walkthrough.md",
                    "localization_validation_walkthrough.md",
                    "sample_time_proposal.md"]

# Companions that cite their own numbered sections (the walkthroughs). Only
# here is a bare `§N` ambiguous between the file and the spec.
const SELF_CITING = ["event_visibility_walkthrough.md",
                     "inbound_periphery_walkthrough.md"]

const MARKER = "<!-- citation link definitions — generated by tools/linkify.jl; do not edit -->"

# Scanned left to right. Code spans and both link forms are matched so the
# replacer can either skip or normalize them; the rest are bare citations.
const SCAN = r"`+[^`]*`+|\[[^\]]*\]\([^)]*\)|\[[^\]]*\]\[[^\]]*\]|§\d+(?:\.\d+)?|§[A-D]\.\d+|Appendix [A-D](?![\w–—-])"

const INLINE = r"^\[([^\]]*)\]\(([^)#]*)#([^)]+)\)$"
const REFERENCE = r"^\[([^\]]*)\]\[([^\]]*)\]$"

iscitation(tok) = startswith(tok, "§") || startswith(tok, "Appendix ")

"Citation key for a token: `§9.4` → `9.4`, `Appendix C` → `C`."
key(tok) = startswith(tok, "§") ? tok[nextind(tok, 1):end] : tok[end:end]

"Reference label for a citation key: `9.4` → `s9-4`, `D.7` → `sD-7`, `C` → `sC`."
label(k) = "s" * replace(k, "." => "-")

"The file's own top-level section numbers — `§N` tokens it may be citing itself with."
function ownsections(file)
    hs = headings(joinpath(DESIGN, file))
    return Set(h.number for h in hs if h.number !== nothing && !occursin('.', h.number))
end

"""
    relink!(file, targets; own) -> (nlinks, ambiguous)

Normalize every citation in `file` to `[tok][label]` form and regenerate the
definitions block. Bare tokens naming one of `own`'s section numbers are
skipped and returned as `(lineno, token)` pairs.
"""
function relink!(file, targets; own = Set{String}())
    isspec = file == SPEC
    path = joinpath(DESIGN, file)
    lines = readlines(path)

    # the definitions block owns everything from the marker to EOF
    stop = findfirst(==(MARKER), lines)
    stop === nothing || (lines = lines[1:stop-1])
    while !isempty(lines) && isempty(strip(lines[end]))
        pop!(lines)
    end

    infence = false
    n = 0
    ambiguous = Tuple{Int,String}[]
    citable(k) = haskey(targets, k)
    for (i, line) in pairs(lines)
        startswith(line, "```") && (infence = !infence; continue)
        (infence || startswith(line, "#")) && continue
        lines[i] = replace(line, SCAN => function (tok)
            startswith(tok, "`") && return tok             # code span
            if startswith(tok, "[")
                m = match(INLINE, tok)
                if m !== nothing                           # legacy inline link
                    iscitation(m[1]) && citable(key(m[1])) || return tok
                    m[2] == SPEC || (m[2] == "" && isspec) || return tok
                    n += 1                                 # a companion's own-file
                    return "[$(m[1])][$(label(key(m[1])))]"  # links stay explicit
                end
                m = match(REFERENCE, tok)
                if m !== nothing                           # normalize the label
                    iscitation(m[1]) && citable(key(m[1])) || return tok
                    n += 1
                    return "[$(m[1])][$(label(key(m[1])))]"
                end
                return tok                                 # non-anchor link
            end
            k = key(tok)                                   # bare citation
            if k in own
                push!(ambiguous, (i, tok))
                return tok
            end
            citable(k) || return tok                       # dangling: check_refs reports it
            n += 1
            return "[$tok][$(label(k))]"
        end)
    end

    # regenerate the definitions block from the labels the body actually uses;
    # fences are skipped and the `s` prefix required so code like `x[1][2]`
    # never reads as a reference link
    used = Set{String}()
    infence = false
    for line in lines
        startswith(line, "```") && (infence = !infence; continue)
        infence && continue
        for m in eachmatch(r"\]\[(s[A-D0-9][A-Za-z0-9-]*)\]", line)
            push!(used, m[1])
        end
    end
    bylabel = Dict(label(k) => slug for (k, slug) in targets)
    defined = sort!([l for l in used if haskey(bylabel, l)])
    unknown = sort!([l for l in used if !haskey(bylabel, l)])
    isempty(unknown) ||
        println("    warn: $file uses labels with no citable heading: ", unknown)
    if !isempty(defined)
        prefix = isspec ? "" : SPEC
        push!(lines, "", MARKER)
        for l in defined
            push!(lines, "[$l]: $prefix#$(bylabel[l])")
        end
    end
    write(path, join(lines, "\n") * "\n")
    return n, ambiguous
end

"""
    toc(hs) -> Vector{String}

The `## Contents` block. Parts and appendices sit at the outer level, chapters
and the `D.x` glossary groups one level in, sections two. `####` headings are
not listed.
"""
function toc(hs)
    out = ["## Contents", ""]
    for (i, h) in enumerate(hs)
        (i == 1 || h.level >= 4 || h.text == "Contents") && continue
        isappendix = h.number !== nothing && occursin(r"^[A-D]", h.number)
        indent = h.level == 1 ? "" :               # parts
                 h.level == 2 ? (isappendix ? "" : "  ") :
                 isappendix ? "  " : "    "        # D.x groups vs. N.M sections
        push!(out, "$indent- [$(h.text)](#$(h.slug))")
    end
    push!(out, "")
    return out
end

"Regenerate the spec's `## Contents` between the front matter and `# Part I`."
function retoc!(hs)
    path = joinpath(DESIGN, SPEC)
    lines = readlines(path)
    part1 = findfirst(startswith("# Part I"), lines)
    part1 === nothing && error("`# Part I` not found")
    old = findfirst(isequal("## Contents"), lines)
    if old !== nothing
        old < part1 || error("`## Contents` is not in the front matter")
        deleteat!(lines, old:part1-1)
        part1 = findfirst(startswith("# Part I"), lines)
    end
    block = [toc(hs); "---"; ""]
    splice!(lines, part1:part1-1, block)
    write(path, join(lines, "\n") * "\n")
    return count(l -> startswith(strip(l), "- ["), block)
end

hs = headings(joinpath(DESIGN, SPEC))
tg = targets(hs)
dup = collisions(hs)
isempty(dup) || println("slug collisions resolved by suffix: ", dup)

println("relink")
println("  ", rpad(SPEC, 42), lpad(first(relink!(SPEC, tg)), 5), " links")
for f in COMPANIONS
    n, ambiguous = relink!(f, tg;
                           own = f in SELF_CITING ? ownsections(f) : Set{String}())
    println("  ", rpad(f, 42), lpad(n, 5), " links")
    for (lineno, tok) in ambiguous
        println("    warn: $f:$lineno bare $tok also names this file's own section",
                " — write the link explicitly")
    end
end
println("  contents: ", retoc!(hs), " entries")
