module FlightPhysicsPlotsExt

using Plots, LaTeXStrings, DataStructures, StructArrays, StaticArrays, Interpolations, LinearAlgebra
using RecursiveArrayTools: VectorOfArray

using FlightCore.Sim: TimeSeries, get_data, get_components
using FlightCore.Plotting: Plotting, make_plots


######################################################
######################## Types #######################

using FlightPhysics.Types: Ranged

@recipe function f(ts::TimeSeries{<:Ranged{T}}) where {T}

    xguide --> L"$t \: (s)$"
    return ts._t, T.(ts._data)

end



######################################################
###################### Attitude ######################

using FlightPhysics.Attitude: Abstract3DRotation, REuler

#if no specific method available, convert to REuler for plotting
@recipe function f(ts::TimeSeries{<:Abstract3DRotation}; rot_ref = "", rot_target = "")

    return TimeSeries(ts._t, [REuler(v) for v in ts._data])

end

@recipe function f(ts::TimeSeries{<:REuler}; rot_ref = "", rot_target = "")

    label --> ["Heading" "Inclination" "Bank"]
    yguide --> hcat(L"$\psi_{%$rot_ref %$rot_target} \ (deg)$",
                    L"$\theta_{%$rot_ref %$rot_target} \ (deg)$",
                    L"$\phi_{%$rot_ref %$rot_target} \ (deg)$")
    ts_split --> :v #custom TimeSeries attribute
    link --> :none

    data = rad2deg.(hcat(ts.ψ._data, ts.θ._data, ts.φ._data)') #
    return TimeSeries(ts._t, data)

end


######################################################
##################### Geodesy ########################

using FlightPhysics.Geodesy: Abstract2DLocation, LatLon, Altitude

#if no specific method available, convert to LatLon for plotting
@recipe function fp(ts::TimeSeries{<:Abstract2DLocation})

    return TimeSeries(ts._t, [LatLon(v) for v in ts._data])

end

@recipe function fp(ts::TimeSeries{<:LatLon})

    title --> ["Latitude" "Longitude"]
    label --> ["Latitude" "Longitude"]
    yguide --> [L"$\varphi \ (deg)$" L"$\lambda \ (deg)$"]
    ts_split --> :v

    data = hcat(rad2deg.(ts.ϕ._data), rad2deg.(ts.λ._data))' |> collect
    return TimeSeries(ts._t, data)

end

@recipe function fp(ts::TimeSeries{<:Altitude{D}}) where {D}

    title --> "Altitude ($(string(D)))"
    label --> "Altitude ($(string(D)))"
    yguide --> L"$h \ (m)$"

    return TimeSeries(ts._t, Float64.(ts._data))

end


######################################################
##################### Kinematics #####################

using FlightPhysics.Geodesy: Cartesian, ltf
using FlightPhysics.Kinematics: KinData

# #@userplot allows defining a custom plot for a specific dataset without having
# #to create a custom type for dispatch. we just wrap the data in the userplot
# #type generated by Plots, and is received inside the recipe in its field "args"
@userplot TrajectoryPlot
@recipe function f(t3d::TrajectoryPlot)

    # https://daschw.github.io/recipes/#series_recipes

    r_eb_e = t3d.args #Vector{SVector{3, Float64}}
    n = length(r_eb_e)

    q_en0 = ltf(Cartesian(r_eb_e[1])) #ECEF to NED rotation for t=0
    Δr_eb_e = [x - r_eb_e[1] for x in r_eb_e]
    Δr_eb_n0 = [q_en0'(x) for x in Δr_eb_e]
    voa = VectorOfArray(Δr_eb_n0)
    #switch from NED to ENU
    North = voa[1,:]
    East = voa[2,:]
    Down = voa[3,:]
    path = (x = East, y = North, z = -Down)

    x_ext, y_ext, z_ext = map(extrema, (path.x, path.y, path.z))
    x_mid, y_mid, z_mid = map(v -> 0.5sum(v), (x_ext, y_ext, z_ext))
    x_span, y_span, z_span = map(v -> v[2] - v[1], (x_ext, y_ext, z_ext))
    span = max(x_span, y_span, z_span)

    x_bounds = (x_mid - 0.5span, x_mid + 0.5span)
    y_bounds = (y_mid - 0.5span, y_mid + 0.5span)
    z_bounds = (z_mid - 0.5span, z_mid + 0.5span)

    #path projections onto the coordinate planes
    path_xp = StructArray((x = fill(x_bounds[1], n), y = path.y, z = path.z))
    path_yp = StructArray((x = path.x, y = fill(y_bounds[1], n), z = path.z))
    path_zp = StructArray((x = path.x, y = path.y, z = fill(z_bounds[1], n)))

    #--> sets default values, which can be overridden by each series using :=
    # linewidth --> 3
    markersize --> 6
    xguide --> L"$\Delta E \ (m)$"
    yguide --> L"$\Delta N \ (m)$"
    zguide --> L"$\Delta U\ (m)$"
    legend --> false

    xlims --> x_bounds
    ylims --> y_bounds
    zlims --> z_bounds

    #projection lines for start and end points
    linecolor --> :lightgray
    for (path_prj, idx) in Iterators.product((path_xp, path_yp, path_zp), (1, n))
        @series begin
            linestyle := :dashdotdot
            # linewidth := 2
            [path_prj.x[idx], path.x[idx]], [path_prj.y[idx], path.y[idx]], [path_prj.z[idx], path.z[idx]]
        end
    end

    #3D path, path projections and start-end markers
    for (p, c) in zip((path_xp, path_yp, path_zp, path),
                      (:darkgray, :darkgray, :darkgray, :blue))

        @series begin
            linestyle := :solid
            seriestype := :path3d
            linecolor := c
            p.x, p.y, p.z
        end
        @series begin
            seriestype := :scatter3d
            markercolor := :green
            [p.x[1]], [p.y[1]], [p.z[1]]
        end
        @series begin
            seriestype := :scatter3d
            markercolor := :red
            [p.x[end]], [p.y[end]], [p.z[end]]
        end

    end

    return nothing

end


function Plotting.make_plots(ts::TimeSeries{<:KinData}; kwargs...)

    pd = OrderedDict{Symbol, Plots.Plot}()

    pd[:e_nb] = plot(
        ts.q_nb; #will automatically be converted to REuler for plotting
        plot_title = "Attitude (Vehicle/NED)",
        rot_ref = "n", rot_target = "b",
        kwargs...)

    #will be automatically converted to LatLon for plotting
    #remove the title added by the LatLon TH recipe
    subplot_latlon = plot(
        ts.n_e;
        title = "",
        ts_split = :v,
        kwargs...)

    #remove the title added by the Altitude TH recipe
    subplot_h = plot(ts.h_e; title = "", kwargs...)
                plot!(ts.h_o; title = "", kwargs...)

    pd[:Ob_geo] = plot(
        subplot_latlon, subplot_h;
        layout = grid(2, 1, heights = [0.67, 0.33]),
        plot_title = "Position (WGS84)",
        kwargs...
        )

    #the Trajectory3D plot should be square (otherwise the lateral margins get
    #absurdly large). choose the larger dimension from the current size
    t3d_dim = max(get(kwargs, :size, Plots.default(:size))...)

    pd[:Ob_t3d] = plot(
        TrajectoryPlot(get_data(ts.r_eb_e));
        plot_title = "Trajectory (Local ENU Frame)",
        camera = (30, 20),
        kwargs...,
        size = (t3d_dim, t3d_dim),
        )

    pd[:ω_wb_b] = plot(
        ts.ω_wb_b;
        plot_title = "Angular Velocity (Vehicle/WA) [Vehicle Axes]",
        label = ["Roll Rate" "Pitch Rate" "Yaw Rate"],
        ylabel = [L"$p \ (rad/s)$" L"$q \ (rad/s)$" L"$r \ (rad/s)$"],
        ts_split = :v,
        kwargs...)

    pd[:v_eb_n] = plot(
        ts.v_eb_n;
        plot_title = "Velocity (Vehicle/ECEF) [NED Axes]",
        label = ["North" "East" "Down"],
        ylabel = [L"$v_{eb}^{N} \ (m/s)$" L"$v_{eb}^{E} \ (m/s)$" L"$v_{eb}^{D} \ (m/s)$"],
        ts_split = :v, link = :none,
        kwargs...)

    subplot_v_gnd = plot(ts.v_gnd; title = "Ground Speed",
        ylabel = L"$v_{gnd} \ (m/s)$", label = "", kwargs...)
    subplot_χ = plot(TimeSeries(ts._t, rad2deg.(ts.χ_gnd._data)); title = "Course Angle",
        ylabel = L"$\chi_{gnd} \ (deg)$", label = "", kwargs...)
    subplot_γ = plot(TimeSeries(ts._t, rad2deg.(ts.γ_gnd._data)); title = "Flight Path Angle",
        ylabel = L"$\gamma_{gnd} \ (deg)$", label = "", kwargs...)

    pd[:vχγ] = plot(subplot_v_gnd, subplot_χ, subplot_γ;
        plot_title = "Velocity (Vehicle/ECEF) [NED Axes]",
        layout = (3,1),
        link = :none,
        kwargs...)

    pd[:v_eb_b] = plot(
        ts.v_eb_b;
        plot_title = "Velocity (Vehicle/ECEF) [Vehicle Axes]",
        ylabel = [L"$v_{eb}^{x_b} \ (m/s)$" L"$v_{eb}^{y_b} \ (m/s)$" L"$v_{eb}^{z_b} \ (m/s)$"],
        ts_split = :v,
        link = :none,
        kwargs...)

    # pd[:ω_ew_n] = plot(
    #     ts.ω_ew_n;
    #     plot_title = "Wander-Azimuth Transport Rate (WA/ECEF) [NED Axes]",
    #     ylabel = L"$\omega_{el}^{l} \ (rad/s)$",
    #     ts_split = :h,
    #     kwargs...)

    return pd

end


######################################################
####################### Dynamics #####################

using FlightPhysics.Dynamics: Wrench, DynamicsData, g₀

@recipe function f(ts::TimeSeries{<:Wrench}; wr_frame = "", wr_source = "")

    layout := (1, 2)
    seriestype --> :path

    @series begin
        subplot := 1
        title --> "Force"
        yguide --> L"$F_{O%$wr_frame \ (%$wr_source)}^{%$wr_frame} \ (N)$"
        ts_split --> :none
        ts.F
    end

    @series begin
        subplot := 2
        title --> "Torque"
        yguide --> L"$\tau_{O%$wr_frame \ (%$wr_source)}^{%$wr_frame} \ (N \ m)$"
        ts_split --> :none
        ts.τ
    end

end

function Plotting.make_plots(ts::TimeSeries{<:DynamicsData}; kwargs...)

    pd = OrderedDict{Symbol, Plots.Plot}()

    pd[:g_c] = plot(ts.g_c_c;
        plot_title = "Gravity at CoM [CoM Axes]",
        ylabel = hcat(
            L"$g_{c}^{x_c} \ (m / s^2)$",
            L"$g_{c}^{y_c} \ (m / s^2)$",
            L"$b_{c}^{z_c} \ (m / s^2)$"),
        ts_split = :v, link = :none,
        kwargs...)

    pd[:wr_ext_c] = plot(ts.wr_Σ_c;
        plot_title = "External Wrench at CoM [CoM Axes]",
        wr_source = "ext", wr_frame = "c",
        kwargs...)

    pd[:wr_ext_b] = plot(ts.wr_Σ_b;
        plot_title = "External Wrench at Ob [Body Axes]",
        wr_source = "ext", wr_frame = "b",
        kwargs...)

    pd[:hr_b] = plot(ts.ho_Σ_b;
        plot_title = "Internal Angular Momentum [Body Axes]",
        ylabel = hcat(
            L"$h_{Ob \ (r)}^{x_b} \ (kg \ m^2 / s)$",
            L"$h_{Ob \ (r)}^{y_b} \ (kg \ m^2 / s)$",
            L"$h_{Ob \ (r)}^{z_b} \ (kg \ m^2 / s)$"),
        ts_split = :v, link = :none,
        kwargs...)

    pd[:α_eb_b] = plot(ts.ω̇_eb_b;
        plot_title = "Angular Acceleration (Body/ECEF) [Body Axes]",
        ylabel = hcat(
            L"$\alpha_{eb}^{x_b} \ (rad/s^2)$",
            L"$\alpha_{eb}^{y_b} \ (rad/s^2)$",
            L"$\alpha_{eb}^{z_b} \ (rad/s^2)$"),
        ts_split = :v,
        kwargs...)

    pd[:a_eb_b] = plot(ts.a_eb_b;
        plot_title = "Linear Acceleration (Body/ECEF) [Body Axes]",
        ylabel = hcat(
            L"$a_{eb}^{x_b} \ (m/s^{2})$",
            L"$a_{eb}^{y_b} \ (m/s^{2})$",
            L"$a_{eb}^{z_b} \ (m/s^{2})$"),
        ts_split = :v,
        kwargs...)

    pd[:f_c_c] = plot(TimeSeries(ts._t, ts.f_c_c._data / g₀);
        plot_title = "Specific Force at CoM [CoM Axes]",
        ylabel = hcat(
            L"$f_{c}^{x_c} \ (g)$",
            L"$f_{c}^{y_c} \ (g)$",
            L"$f_{c}^{z_c} \ (g)$"),
        ts_split = :v, link = :none,
        kwargs...)

    return pd

end


######################################################
###################### Atmosphere ####################

using FlightPhysics.Atmosphere: AirData

function Plotting.make_plots(ts::TimeSeries{<:AirData}; kwargs...)

    pd = OrderedDict{Symbol, Plots.Plot}()

    pd[:v_ew_n] = plot(ts.v_ew_n;
        plot_title = "Velocity (Wind / ECEF) [NED Axes]",
        label = ["North" "East" "Down"],
        ylabel = [L"$v_{ew}^{N} \ (m/s)$" L"$v_{ew}^{E} \ (m/s)$" L"$v_{ew}^{D} \ (m/s)$"],
        ts_split = :v,
        kwargs...)

    pd[:v_ew_b] = plot(ts.v_ew_b;
        plot_title = "Velocity (Wind / ECEF) [Vehicle Axes]",
        ylabel = [L"$v_{ew}^{x_b} \ (m/s)$" L"$v_{ew}^{y_b} \ (m/s)$" L"$v_{ew}^{z_b} \ (m/s)$"],
        ts_split = :v,
        kwargs...)

    pd[:v_wb_b] = plot(ts.v_wb_b;
        plot_title = "Velocity (Vehicle / Wind) [Vehicle Axes]",
        ylabel = [L"$v_{eb}^{x_b} \ (m/s)$" L"$v_{eb}^{y_b} \ (m/s)$" L"$v_{eb}^{z_b} \ (m/s)$"],
        ts_split = :v,
        kwargs...)

        subplot_a = plot(ts.a;
            title = "Speed of Sound", ylabel = L"$a \ (m/s)$",
            label = "", kwargs...)

        subplot_ρ = plot(ts.ρ;
            title = "Density", ylabel = L"$\rho \ (kg/m^3)$",
            label = "", kwargs...)

        subplot_μ = plot(ts.μ;
            title = "Dynamic Viscosity", ylabel = L"$\mu \ (Pa \ s)$",
            label = "", kwargs...)

    pd[:ρ_a] = plot(subplot_ρ, subplot_a, subplot_μ;
        plot_title = "Freestream Properties",
        layout = (3,1),
        kwargs...,
        )


        subplot_T = plot(
            TimeSeries(ts._t, hcat(ts.T._data, ts.Tt._data)' |> collect);
            title = "Temperature",
            label = ["Static"  "Total"],
            ylabel = L"$T \ (K)$",
            ts_split = :none, kwargs...)

        subplot_p = plot(
            TimeSeries(ts._t, 1e-3*hcat(ts.p._data, ts.pt._data)' |> collect);
            title = "Pressure",
            label = ["Static"  "Total"],
            ylabel = L"$p \ (kPa)$",
            ts_split = :none, kwargs...)

    pd[:T_p] = plot(subplot_T, subplot_p;
        plot_title = "Freestream Properties",
        layout = (2,1),
        kwargs...
        )

        subplot_airspeed = plot(
            TimeSeries(ts._t, hcat(ts.TAS._data, ts.EAS._data, ts.CAS._data)' |> collect);
            title = "Airspeed",
            label = ["True" "Equivalent" "Calibrated"],
            ylabel = L"$v \ (m/s)$",
            ts_split = :none, kwargs...)

        subplot_Mach = plot(ts.M;
            title = "Mach", ylabel = L"M",
            label = "", kwargs...)

        subplot_q = plot(TimeSeries(ts._t, ts.q._data/1000);
            title = "Dynamic Pressure", ylabel = L"$q \ (kPa)$",
            label = "", kwargs...)

    l3 = @layout [a{0.5w} [b; c{0.5h}]]

    pd[:airspeed_M_q] = plot(
        subplot_airspeed, subplot_Mach, subplot_q;
        layout = l3,
        plot_title = "Freestream Properties",
        kwargs...,
        )

    return pd

end


######################################################
###################### Control #######################

using FlightPhysics.Control: PIVectorY, PIDOutput, PIDVectorOutput

function Plotting.make_plots(ts::TimeSeries{<:PIVectorY}; kwargs...)

    pd = OrderedDict{Symbol, Plots.Plot}()

    input = plot(ts.input; title = "Input", ylabel = L"$e$", kwargs...)
    output = plot(ts.output; title = "Output", ylabel = L"$y$", kwargs...)

    pd[:sf] = plot(input, output;
        plot_title = "Input & Output",
        layout = (2,1),
        link = :y,
        kwargs...)

    k_p = plot(ts.k_p; title = "Proportional Gain", ylabel = L"$k_p$", kwargs...)
    k_i = plot(ts.k_i; title = "Integral Gain", ylabel = L"$k_i$", kwargs...)
    k_l = plot(ts.k_l; title = "Leak Factor", ylabel = L"$k_d$", kwargs...)

    pd[:p1] = plot(k_p, k_i, k_l;
        plot_title = "Parameters",
        layout = (3,1),
        link = :none,
        kwargs...)

    β_p = plot(ts.β_p; title = "Proportional Input Weighting", ylabel = L"$\beta_p$", kwargs...)
    bound_lo = plot(ts.bound_lo; title = "Lower Output Bound", ylabel = L"$y_{min}$", kwargs...)
    bound_hi = plot(ts.bound_hi; title = "Upper Output Bound", ylabel = L"$y_{max}$", kwargs...)

    pd[:p2] = plot(β_p, bound_lo, bound_hi;
        plot_title = "Parameters",
        layout = (3,1),
        link = :none,
        kwargs...)

    sat_ext = plot(ts.sat_ext; title = "External Saturation Input", ylabel = "", kwargs...)
    sat_out = plot(ts.sat_out; title = "Output Saturation", ylabel = "", kwargs...)
    int_halted = plot(ts.int_halted; title = "Integrator Halted", ylabel = "", kwargs...)

    pd[:awu] = plot(sat_ext, sat_out, int_halted;
        plot_title = "Anti-Windup",
        layout = (3,1),
        kwargs...)

    u_p = plot(ts.u_p; title = "Input", ylabel = L"$u_p$", kwargs...)
    y_p = plot(ts.y_p; title = "Output", ylabel = L"$y_p$", kwargs...)

    pd[:prop] = plot(u_p, y_p;
        plot_title = "Proportional Path",
        layout = (2,1),
        link = :y,
        kwargs...)

    u_i = plot(ts.u_i; title = "Input", ylabel = L"$u_i$", kwargs...)
    y_i = plot(ts.y_i; title = "Output", ylabel = L"$y_i$", kwargs...)

    pd[:int] = plot(u_i, y_i, int_halted;
        plot_title = "Integral Path",
        layout = (3,1),
        link = :y,
        kwargs...)

    out_free = plot(ts.out_free; title = "Free", ylabel = L"$y_{free}$", kwargs...)
    output = plot(ts.output; title = "Actual", ylabel = L"$y$", kwargs...)

    pd[:output] = plot(out_free, output, sat_out;
        plot_title = "PID Output",
        layout = (3,1),
        link = :y,
        kwargs...)

    return pd

end


function Plotting.make_plots(ts::Union{TimeSeries{<:PIDOutput},
                                       TimeSeries{<:PIDVectorOutput}}; kwargs...)

    pd = OrderedDict{Symbol, Plots.Plot}()

    input = plot(ts.input; title = "Input", ylabel = L"$e$", kwargs...)
    output = plot(ts.output; title = "Output", ylabel = L"$y$", kwargs...)

    pd[:sf] = plot(input, output;
        plot_title = "Input & Output",
        layout = (2,1),
        link = :y,
        kwargs...)

    k_p = plot(ts.k_p; title = "Proportional Gain", ylabel = L"$k_p$", kwargs...)
    k_i = plot(ts.k_i; title = "Integral Gain", ylabel = L"$k_i$", kwargs...)
    k_d = plot(ts.k_d; title = "Derivative Gain", ylabel = L"$k_d$", kwargs...)
    τ_f = plot(ts.τ_f; title = "Derivative Filter Time Constant", ylabel = L"$\tau_f$", kwargs...)

    pd[:p1] = plot(k_p, k_i, k_d, τ_f;
        plot_title = "Parameters",
        layout = (4,1),
        link = :none,
        kwargs...)

    β_p = plot(ts.β_p; title = "Proportional Input Weighting", ylabel = L"$\beta_p$", kwargs...)
    β_d = plot(ts.β_d; title = "Derivative Input Weighting", ylabel = L"$\beta_d$", kwargs...)
    bound_lo = plot(ts.bound_lo; title = "Lower Output Bound", ylabel = L"$y_{min}$", kwargs...)
    bound_hi = plot(ts.bound_hi; title = "Upper Output Bound", ylabel = L"$y_{max}$", kwargs...)

    pd[:p2] = plot(β_p, β_d, bound_lo, bound_hi;
        plot_title = "Parameters",
        layout = (4,1),
        link = :none,
        kwargs...)

    sat_ext = plot(ts.sat_ext; title = "External Saturation Input", ylabel = "", kwargs...)
    sat_out = plot(ts.sat_out; title = "Output Saturation", ylabel = "", kwargs...)
    int_halted = plot(ts.int_halted; title = "Integrator Halted", ylabel = "", kwargs...)

    pd[:awu] = plot(sat_ext, sat_out, int_halted;
        plot_title = "Anti-Windup",
        layout = (3,1),
        kwargs...)

    u_p = plot(ts.u_p; title = "Input", ylabel = L"$u_p$", kwargs...)
    y_p = plot(ts.y_p; title = "Output", ylabel = L"$y_p$", kwargs...)

    pd[:prop] = plot(u_p, y_p;
        plot_title = "Proportional Path",
        layout = (2,1),
        link = :y,
        kwargs...)

    u_i = plot(ts.u_i; title = "Input", ylabel = L"$u_i$", kwargs...)
    y_i = plot(ts.y_i; title = "Output", ylabel = L"$y_i$", kwargs...)

    pd[:int] = plot(u_i, y_i, int_halted;
        plot_title = "Integral Path",
        layout = (3,1),
        link = :y,
        kwargs...)

    u_d = plot(ts.u_d; title = "Input", ylabel = L"$u_d$", kwargs...)
    y_d = plot(ts.y_d; title = "Output", ylabel = L"$y_d$", kwargs...)

    pd[:der] = plot(u_d, y_d;
        plot_title = "Derivative Path",
        layout = (3,1),
        link = :y,
        kwargs...)

    out_free = plot(ts.out_free; title = "Free", ylabel = L"$y_{free}$", kwargs...)
    output = plot(ts.output; title = "Actual", ylabel = L"$y$", kwargs...)

    pd[:output] = plot(out_free, output, sat_out;
        plot_title = "PID Output",
        layout = (3,1),
        link = :y,
        kwargs...)

    return pd

end

######################################################
################## Propellers ########################

using FlightPhysics.Propellers


@recipe function f(airfoil::Propellers.AbstractAirfoil)

    α = range(-π/6, π/3, length = 100)
    M = range(0, 1.5, length = 6)
    iter = Iterators.product(α, M)

    cL_data = [Propellers.cL(airfoil, α, M) for (α, M) in iter]
    cD_data = [Propellers.cD(airfoil, α, M) for (α, M) in iter]
    cL_α_data = [Propellers.cL_α(airfoil, α, M) for (α, M) in iter]

    layout := (1, 3)
    plot_title --> "Airfoil Characteristics ($(typeof(airfoil)))"
    xguide --> L"\alpha \ (deg)"
    label --> latexstring.("M = " .* string.(M'))
    link --> :x

    @series begin
        subplot := 1
        title := L"c_L"
        rad2deg.(α), cL_data
    end

    @series begin
        subplot := 2
        title := L"c_{L, \alpha}"
        rad2deg.(α), cL_α_data
    end

    @series begin
        subplot := 3
        title := L"c_D"
        rad2deg.(α), cD_data
    end
end


function Plotting.make_plots(airfoil::Propellers.AbstractAirfoil; kwargs...)
    pd = OrderedDict{Symbol, Plots.Plot}()
    pd[:aerodynamics] = plot(airfoil; kwargs...)
    return pd
end


function Plotting.make_plots(lookup::Propellers.Lookup; Mt_ref = 0.0, Δβ_ref = 0.0, kwargs...)
    pd = OrderedDict{Symbol, Plots.Plot}()

    J_bounds, Mt_bounds, Δβ_bounds = bounds(lookup)

    y_labels =[L"C_{Fx}", L"C_{Mx}", L"C_{Fz, \alpha}", L"C_{Mz, \alpha}", L"C_P", L"\eta_p"]
    titles =["Traction Coefficient", "Torque Coefficient", "Off-Axis Force Coefficient Derivative",
              "Off-Axis Moment Coefficient Derivative", "Power Coefficient", "Propulsive Efficiency"]

    #sweep J, parametric in Δβ
    if Δβ_bounds[1] < Δβ_bounds[2] #only if Δβ dimension is non-singleton (variable pitch)
        J = range(J_bounds..., length = 50)
        Δβ_vec = range(Δβ_bounds..., length = 5)

        data =[lookup(J, Mt_ref, Δβ) for (J, Δβ) in Iterators.product(J, Δβ_vec)]
        (; C_Fx, C_Mx, C_Fz_α, C_Mz_α, C_P, η_p) = data |> StructArray |> StructArrays.components

        label = latexstring.("\\Delta \\beta = " .* string.(rad2deg.(Δβ_vec')) .* "^\\circ")

        subplots = [plot(J, c; title = titles[i], label = label, xlabel = L"J", ylabel = y_labels[i], kwargs...)
                    for (i, c) in enumerate((C_Fx, C_Mx, C_Fz_α, C_Mz_α, C_P, η_p))]

        pd[:J_Δβ] = plot(subplots...;
            layout = (2, 3),
            plot_title = "Propeller Coefficients (Mt = $Mt_ref)",
        )
    end

    #sweep J, parametric in Mt
    if Mt_bounds[1] < Mt_bounds[2] #only if Mt dimension is non-singleton
        J = range(J_bounds..., length = 50)
        Mt = range(Mt_bounds..., length = 5)

        data =[lookup(J, Mt, Δβ_ref) for (J, Mt) in Iterators.product(J, Mt)]
        (; C_Fx, C_Mx, C_Fz_α, C_Mz_α, C_P, η_p) = data |> StructArray |> StructArrays.components

        label = latexstring.("M_{tip} = ".*string.(Mt'))

        subplots = [plot(J, c; title = titles[i], label = label, xlabel = L"J", ylabel = y_labels[i], kwargs...)
                    for (i, c) in enumerate((C_Fx, C_Mx, C_Fz_α, C_Mz_α, C_P, η_p))]

        pd[:J_Mt] = plot(subplots...;
            layout = (2, 3),
            plot_title = "Propeller Coefficients (Δβ = $(rad2deg(Δβ_ref))°)",
        )
    end

    return pd
end


######################################################
###################### Piston ########################

using FlightPhysics.Piston


function Plotting.make_plots(lookup::Piston.PistonEngineLookup; kwargs...)

    pd = OrderedDict{Symbol, Plots.Plot}()

    n_cont = range(0.0, 1.2, length = 100)
    μ_cont = range(0.1, 1.0, length = 100)
    δ_cont = range(1.0, 0.0, length = 100)

    n_param =[0, 0.2, 0.4, 0.6, 0.7, 0.8, 0.9, 1.0]
    μ_param =[0, 0.2, 0.4, 0.6, 0.8, 1.0]
    δ_param = [1.0, 0.8, 0.6, 0.4, 0.2, 0]


    π_std_1 =[lookup.π_std(n, μ) for n in n_cont, μ in μ_param]
    p_std_1 = plot(n_cont, π_std_1;
        title = "Normalized Power (Sea Level, Part Throttle) vs Normalized RPM",
        xlabel = L"$n$",
        ylabel = L"$\pi_{std}$",
        label = latexstring.("\\mu = " .* string.(μ_param')),
        legend = :topleft,
        kwargs...
    )

    #Lycoming O-360 Operator's Manual, Fig. 3-21 Left
    π_std_2 =[lookup.π_std(n, μ) for μ in μ_cont, n in n_param]
    p_std_2 = plot(μ_cont, π_std_2;
        title = "Normalized Power (Sea Level, Part Throttle) vs Normalized MAP",
        xlabel = L"$\mu$",
        ylabel = L"$\pi_{std}$",
        label = latexstring.("n = " .* string.(n_param')),
        legend = :topleft,
        kwargs...
    )

    π_wot_1 =[lookup.π_wot(n, δ) for n in n_cont, δ in δ_param]
    p_wot_1 = plot(n_cont, π_wot_1;
        title = "Normalized Power (Altitude, Full Throttle) vs Normalized RPM",
        xlabel = L"$n$",
        ylabel = L"$\pi_{wot}$",
        label = latexstring.("\\delta = " .* string.(δ_param')),
        legend = :topleft,
        kwargs...
    )

    #Lycoming O-360 Operator's Manual, Fig. 3-21 Right
    π_wot_2 =[lookup.π_wot(n, δ) for δ in δ_cont, n in n_param]
    p_wot_2 = plot(δ_cont, π_wot_2;
        title = "Normalized Power (Altitude, Full Throttle) vs Normalized Ambient Pressure",
        xlabel = L"$\delta$",
        ylabel = L"$\pi_{wot}$",
        xflip = true, # Flip X-axis so altitude goes UP to the right
        label = latexstring.("n = " .* string.(n_param')),
        legend = :bottomleft,
        kwargs...
    )

    pd[:performance_map] = plot(p_std_1, p_std_2, p_wot_1, p_wot_2;
        layout = (2, 2),
        plot_title = "Engine Maps",
        kwargs...
    )

    return pd
end


######################################################
################### LandingGear ######################

using FlightPhysics.LandingGear: StrutY, ContactY

function Plotting.make_plots(ts::TimeSeries{<:StrutY}; kwargs...)

    pd = OrderedDict{Symbol, Any}()

    subplot_ξ = plot(ts.ξ;
        title = "Elongation", ylabel = L"$\xi \ (m)$",
        label = "", kwargs...)

    subplot_ξ_dot = plot(ts.ξ_dot;
        title = "Elongation Rate", ylabel = L"$\dot{\xi} \ (m/s)$",
        label = "", kwargs...)

    subplot_F = plot(ts.F_dmp_zs;
        title = "Force", ylabel = L"$F \ (N)$",
        label = "", kwargs...)

    pd[:dmp] = plot(subplot_ξ, subplot_ξ_dot, subplot_F;
        plot_title = "Damper",
        layout = (1,3), link = :none,
        kwargs...)

    return pd

end

function Plotting.make_plots(ts::TimeSeries{<:ContactY}; kwargs...)

    pd = OrderedDict{Symbol, Any}()

    (μ_max_x, μ_max_y) = get_components(ts.μ_max)
    (μ_eff_x, μ_eff_y) = get_components(ts.μ_eff)

    subplot_μ_roll = plot(ts.μ_roll; title = "Rolling Friction Coefficient",
        ylabel = L"$\mu_{roll}$", label = "", kwargs...)
    subplot_μ_skid = plot(ts.μ_skid; title = "Skidding Friction Coefficient",
        ylabel = L"$\mu_{skid}$", label = "", kwargs...)

    pd[:srf] = plot(subplot_μ_roll, subplot_μ_skid;
        plot_title = "Surface Friction",
        layout = (1,2), link = :y,
        kwargs...)

    subplot_κ_br = plot(ts.κ_br; title = "Braking Coefficient",
        ylabel = L"$\alpha_{br}$", label = "", kwargs...)
    subplot_μ_max_x = plot(μ_max_x; title = "Maximum Friction Coefficient",
        ylabel = L"$\mu_{max}^{x}$", label = "", kwargs...)
    subplot_μ_eff_x = plot(μ_eff_x; title = "Effective Friction Coefficient",
        ylabel = L"$\mu^{x}$", label = "", kwargs...)

    pd[:μ_x] = plot(subplot_κ_br, subplot_μ_max_x, subplot_μ_eff_x;
        plot_title = "Longitudinal Friction",
        layout = (1,3),
        kwargs...)

    subplot_ψ_cv = plot(ts._t, rad2deg.(ts.ψ_cv._data); title = "Tire Slip Angle",
        ylabel = L"$\psi_{cv} \ (deg)$", label = "", kwargs...)
    subplot_μ_max_y = plot(μ_max_y; title = "Maximum Friction Coefficient",
        ylabel = L"$\mu_{max}^{y}$", label = "", kwargs...)
    subplot_μ_eff_y = plot(μ_eff_y; title = "Effective Friction Coefficient",
        ylabel = L"$\mu^{y}$", label = "", kwargs...)

    pd[:μ_y] = plot(subplot_ψ_cv, subplot_μ_max_y, subplot_μ_eff_y;
        plot_title = "Lateral Friction",
        layout = (1,3),
        kwargs...)

    pd[:f_c] = plot(ts.f_c;
        plot_title = "Normalized Contact Force",
        ylabel = [L"$f_{Oc \ (terrain)}^{c}$" L"$f_{Oc \ (terrain)}^{c}$" L"$f_{Oc \ (terrain)}^{c}$"],
        ts_split = :h, link = :none,
        kwargs...)

    pd[:F_c] = plot(ts.F_c;
        plot_title = "Contact Force",
        ylabel = [L"$F_{Oc \ (terrain)}^{c} \ (N)$" L"$F_{Oc \ (terrain)}^{c} \ (N)$" L"$F_{Oc \ (terrain)}^{c} \ (N)$"],
        ts_split = :h, link = :none,
        kwargs...)

    pd[:wr_b] = plot(ts.wr_b;
        plot_title = "Wrench [Vehicle Axes]",
        wr_source = "terrain", wr_frame = "b",
        kwargs...)

    pd[:frc] = make_plots(ts.frc; kwargs...)

    return pd

end


######################################################
#################### AircraftBase ####################

using FlightPhysics.AircraftBase: VehicleY

function Plotting.make_plots(ts::TimeSeries{<:VehicleY}; kwargs...)

    return OrderedDict(
        :systems => make_plots(ts.systems; kwargs...),
        :kinematics => make_plots(ts.kinematics; kwargs...),
        :dynamics => make_plots(ts.dynamics; kwargs...),
        :airflow => make_plots(ts.airflow; kwargs...),
    )

end


end # module
