using Test, StaticArrays, LinearAlgebra, BenchmarkTools, ForwardDiff

include("../src/leaves.jl")
include("../src/declare.jl")
include("../src/assembly.jl")
include("../src/store.jl")
include("../src/executor.jl")
include("../src/build.jl")
include("../src/dataplane.jl")
include("../src/roster.jl")
include("../src/bindings.jl")
include("../src/devices.jl")
include("../src/stepper.jl")
include("../src/sim.jl")
include("../src/localize.jl")
include("../src/library.jl")

include("utils.jl")
include("test_continuous.jl")
include("test_structure.jl")
include("test_discrete.jl")
include("test_hierarchy.jl")
include("test_multirate.jl")
include("test_events.jl")
include("test_localization.jl")
include("test_stepper.jl")
include("test_dataplane.jl")
include("test_roster.jl")
include("test_log.jl")
include("test_devices.jl")
include("test_bindings.jl")
include("test_diagnostics.jl")
